name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: pandaofficial/timeswipe_ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
          git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive
        cd driver
        pwd
        ls -l
        mkdir build64
        cd build64
        cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
        ls -l
        make
        export destdir="$PWD"/timeswipe_`cat ../version`.aarch64
        make VERBOSE=1 DESTDIR=$destdir install
        cp -p -r DEBIAN $destdir
        dpkg-deb --build $destdir && mv *.deb .. && cd .. && rm -rf $build_dir
        
