name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: pandaofficial/timeswipe_ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        apt install -y git #TODO: move to docker
        git clone https://github.com/nlohmann/json driver/3rdParty/nlohmann #XXX: until submodule issue resolved in actions        
        cd driver
        pwd
        ls -l
        mkdir build64
        cd build64
        cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
        ls -l
        make
        export destdir="$PWD"/timeswipe_`cat ../version`.aarch64
        make VERBOSE=1 DESTDIR=$destdir install
        cp -p -r DEBIAN $destdir
        dpkg-deb --build $destdir && mv *.deb .. && cd .. && rm -rf $build_dir
        
