name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: pandaofficial/timeswipe_ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        pwd
        ls -l
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
        ls -l
        make
