on:
  push:
    branches:
      - master

name: Test driver build

jobs:
  test:
    name: Test driver build
    runs-on: ubuntu-latest
    container: pandaofficial/timeswipe_ubuntu
    steps:
        run: |
          git clone https://github.com/nlohmann/json driver/3rdParty/nlohmann #XXX: until submodule issue resolved in actions        
          cd driver
          mkdir build64
          cd build64
          cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
          make
          export destdir="$PWD"/timeswipe_`cat ../version`.aarch64
          make -j DESTDIR=$destdir install
          cp -p -r DEBIAN $destdir
          dpkg-deb --build $destdir

